{ pkgs-unstable
, lib
, config
, ...
}:
let
  cfg = config.services.recyclarr-sync;
in
{
  options.services.recyclarr-sync = {
    enable = lib.mkEnableOption "Enable automated Recyclarr synchronization for Trash Guides";
    interval = lib.mkOption {
      type = lib.types.str;
      default = "daily";
      description = "Systemd timer interval for synchronization";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs-unstable.recyclarr ];

    systemd.services.recyclarr = {
      description = "Recyclarr Trash Guides Synchronization";
      after = [ "network-online.target" "sonarr.service" "radarr.service" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "oneshot";
        User = "olafkfreund";
        Group = "users";
        StateDirectory = "recyclarr";
        RuntimeDirectory = "recyclarr";
        # Path to temporary config
        Environment = "RECYCLARR_CONFIG_DIR=/run/recyclarr";
      };

      script = ''
        set -euo pipefail

        # Extract API Keys from config files
        RADARR_KEY=$(grep -oP '(?<=<ApiKey>).*(?=</ApiKey>)' /mnt/media/radarr/config.xml)
        SONARR_KEY=$(grep -oP '(?<=<ApiKey>).*(?=</ApiKey>)' /mnt/media/sonarr/config.xml)

        if [ -z "$RADARR_KEY" ] || [ -z "$SONARR_KEY" ]; then
          echo "Error: Could not extract API keys from Radarr/Sonarr config files."
          exit 1
        fi

        # Generate configuration file
        cat > /run/recyclarr/recyclarr.yml <<EOF
        # Recyclarr Configuration - Generated by NixOS
        # Documentation: https://recyclarr.dev/

        radarr:
          movies:
            base_url: http://localhost:7878
            api_key: $RADARR_KEY
            include:
              - template: radarr-quality-definition-movie
              - template: radarr-quality-profile-remux-web-1080p
              - template: radarr-custom-formats-hd-bluray-web

        sonarr:
          tv:
            base_url: http://localhost:8989
            api_key: $SONARR_KEY
            include:
              - template: sonarr-quality-definition-series
              - template: sonarr-v4-quality-profile-web-1080p
              - template: sonarr-v4-custom-formats-web-1080p
        EOF

        # Run synchronization
        ${pkgs-unstable.recyclarr}/bin/recyclarr sync --config /run/recyclarr/recyclarr.yml
      '';
    };

    systemd.timers.recyclarr = {
      description = "Daily Recyclarr Synchronization";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = cfg.interval;
        Persistent = true;
      };
    };
  };
}
