{ pkgs-unstable
, lib
, config
, ...
}:
let
  cfg = config.services.recyclarr-sync;
in
{
  options.services.recyclarr-sync = {
    enable = lib.mkEnableOption "Enable automated Recyclarr synchronization for Trash Guides";
    interval = lib.mkOption {
      type = lib.types.str;
      default = "daily";
      description = "Systemd timer interval for synchronization";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs-unstable.recyclarr ];

    systemd.services.recyclarr = {
      description = "Recyclarr Trash Guides Synchronization";
      after = [ "network-online.target" "sonarr.service" "radarr.service" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "oneshot";
        User = "olafkfreund";
        Group = "users";
        StateDirectory = "recyclarr";
        RuntimeDirectory = "recyclarr";
        # API keys come from agenix (same env file arr-suite-mcp uses).
        # Loaded by systemd as root before exec, then exposed to the
        # user-owned recyclarr process via the environment — keeps the
        # values out of /proc and avoids the brittle config.xml regex
        # extraction we used to do here.
        EnvironmentFile = config.age.secrets."arr-suite-mcp-env".path;
        # Path to temporary config
        Environment = "RECYCLARR_CONFIG_DIR=/run/recyclarr";
      };

      script = ''
        set -euo pipefail

        # Sanity-check: arr-suite-mcp-env.age must supply these.
        if [ -z "''${SONARR_API_KEY:-}" ] || [ -z "''${RADARR_API_KEY:-}" ]; then
          echo "Error: SONARR_API_KEY / RADARR_API_KEY not set." >&2
          echo "Check secrets/arr-suite-mcp-env.age and that the EnvironmentFile" >&2
          echo "directive on this unit points at /run/agenix/arr-suite-mcp-env." >&2
          exit 1
        fi

        # Generate configuration file
        cat > /run/recyclarr/recyclarr.yml <<EOF
        # Recyclarr Configuration - Generated by NixOS
        # Documentation: https://recyclarr.dev/

        radarr:
          movies:
            base_url: http://localhost:7878
            api_key: $RADARR_API_KEY
            include:
              - template: radarr-quality-definition-movie
              - template: radarr-quality-profile-remux-web-1080p
              - template: radarr-custom-formats-hd-bluray-web

        sonarr:
          tv:
            base_url: http://localhost:8989
            api_key: $SONARR_API_KEY
            include:
              - template: sonarr-quality-definition-series
              - template: sonarr-v4-quality-profile-web-1080p
              - template: sonarr-v4-custom-formats-web-1080p
        EOF

        # Run synchronization
        ${pkgs-unstable.recyclarr}/bin/recyclarr sync --config /run/recyclarr/recyclarr.yml
      '';
    };

    systemd.timers.recyclarr = {
      description = "Daily Recyclarr Synchronization";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = cfg.interval;
        Persistent = true;
      };
    };
  };
}
