# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, modulesPath
, inputs
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")

    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-cpu-amd-pstate
    inputs.nixos-hardware.nixosModules.common-gpu-amd
    inputs.nixos-hardware.nixosModules.common-hidpi
    inputs.nixos-hardware.nixosModules.common-pc
    inputs.nixos-hardware.nixosModules.common-pc-ssd
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7939da9e-4df7-4851-985a-14c7b94fd15f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E618-4247";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Degraded Fanxiang S101Q (…30717): ~15 MB/s writes (Issue #2185). Archive
  # only; keep nothing here that exists nowhere else.
  fileSystems."/mnt/archives" = {
    device = "/dev/disk/by-uuid/093b3944-a550-4cd0-a320-df12bebc66cd";
    fsType = "ext4";
    options = [
      "nofail"
      "noatime"
      "x-systemd.device-timeout=10s"
      "x-systemd.mount-timeout=60s"
      "X-fstrim.notrim" # the weekly trim crawled on this drive for 10 h
    ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/86cc53e0-e155-4753-ac0d-2d291573476d";
    fsType = "ext4";
    options = [
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
      "exec" # Permit execution of binaries and other executable files
    ];
  };

  # BIWIN M100 1TB SATA SSD for source code (Issue #2165)
  fileSystems."/mnt/code" = {
    device = "/dev/disk/by-uuid/bdd8461e-7d6c-42b6-9cfe-39967825dd42";
    fsType = "ext4";
    options = [
      "nofail"
      "noatime"
      "x-systemd.device-timeout=10s"
    ];
  };

  # Fanxiang S501Q 1TB NVMe (Issue #2182). No nofail: a missing disk must stop
  # the boot, not log in to an empty home on /.
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e31728b8-d79c-41e1-934c-af9b576f4348";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  # 480GB SATA SSD: nix build-dir and nixarchy runner VMs (Issue #2182).
  # nofail on purpose: builds fall back to / so the host can still rebuild.
  fileSystems."/var/lib/nix-build" = {
    device = "/dev/disk/by-uuid/c084fd70-c039-4724-8ebc-0cc78113eb30";
    fsType = "ext4";
    options = [
      "nofail"
      "noatime"
      "x-systemd.device-timeout=10s"
    ];
  };

  # Micron 256GB SATA SSD: Docker data-root (Issue #2182). Docker requires it,
  # see configuration.nix.
  fileSystems."/mnt/img_pool" = {
    device = "/dev/disk/by-uuid/82b43c59-ec6c-4f10-9100-e18372db2337";
    fsType = "ext4";
    options = [
      "nofail"
      "noatime"
      "x-systemd.device-timeout=10s"
    ];
  };

  swapDevices = [ ];

  # SSD I/O scheduler optimization
  # Set optimal scheduler for SSDs (none/noop for better performance)
  services.udev.extraRules = ''
    # Degraded /mnt/archives SSD (Issue #2156): cap its dirty page cache.
    ACTION=="add|change", SUBSYSTEM=="block", ENV{DEVTYPE}=="disk", ENV{ID_SERIAL_SHORT}=="MX_00000000000030717", ATTR{bdi/strict_limit}="1", ATTR{bdi/max_ratio}="1"

    # Automatically set 'none' scheduler for non-rotational drives (SSDs)
    ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
    # BFQ on both NVMe disks so I/O priorities apply. Matched by pattern: the
    # names swap when a disk is added (Issue #2182).
    ACTION=="add|change", KERNEL=="nvme[0-9]n1", ATTR{queue/scheduler}="bfq"
  '';

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
