{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.desktop.gnome;
in
{
  config = mkIf (cfg.enable && cfg.theme.enable) {
    # GTK theming with Gruvbox colors
    gtk = {
      enable = true;

      theme = {
        package = mkDefault pkgs.gruvbox-gtk-theme;
        name = mkDefault (if cfg.theme.variant == "dark" then "Gruvbox-Dark-Medium" else "Gruvbox-Light-BL");
      };

      iconTheme = {
        package = mkDefault pkgs.gruvbox-plus-icons;
        name = mkDefault "Gruvbox-Material-Dark";
      };

      cursorTheme = {
        package = mkDefault pkgs.bibata-cursors;
        name = mkDefault "Bibata-Modern-Classic";
        size = mkDefault 16;
      };

      font = {
        name = mkDefault "Inter";
        size = mkDefault 11;
      };

      gtk3.extraConfig = {
        gtk-application-prefer-dark-theme = cfg.theme.variant == "dark";
      };

      gtk4.extraConfig = {
        gtk-application-prefer-dark-theme = cfg.theme.variant == "dark";
      };
    };

    # Modern Stylix GTK CSS customization (replaces deprecated gtk3/gtk4.extraCss)
    stylix.targets.gtk.extraCss = ''
      /* GENERATED BY COSMIC */
      @define-color window_bg_color rgba(40, 40, 40, 1.00);
      @define-color window_fg_color rgba(255, 251, 245, 1.00);

      @define-color view_bg_color rgba(50, 48, 47, 1.00);
      @define-color view_fg_color rgba(199, 195, 189, 1.00);

      @define-color headerbar_bg_color rgba(40, 40, 40, 1.00);
      @define-color headerbar_fg_color rgba(255, 251, 245, 1.00);
      @define-color headerbar_border_color_color rgba(83, 82, 81, 1.00);
      @define-color headerbar_backdrop_color rgba(40, 40, 40, 1.00);

      @define-color sidebar_bg_color rgba(50, 48, 47, 1.00);
      @define-color sidebar_fg_color rgba(199, 195, 189, 1.00);
      @define-color sidebar_shade_color rgba(0, 0, 0, 0.08);
      @define-color sidebar_backdrop_color rgba(66, 65, 64, 1.00);

      @define-color secondary_sidebar_bg_color rgba(67, 67, 67, 1.00);
      @define-color secondary_sidebar_fg_color rgba(221, 218, 211, 1.00);
      @define-color secondary_sidebar_shade_color rgba(0, 0, 0, 0.08);
      @define-color secondary_sidebar_backdrop_color rgba(82, 82, 82, 1.00);

      @define-color card_bg_color rgba(62, 62, 62, 1.00);
      @define-color card_fg_color rgba(215, 211, 205, 1.00);

      @define-color thumbnail_bg_color rgba(62, 62, 62, 1.00);
      @define-color thumbnail_fg_color rgba(215, 211, 205, 1.00);

      @define-color dialog_bg_color rgba(50, 48, 47, 1.00);
      @define-color dialog_fg_color rgba(199, 195, 189, 1.00);

      @define-color popover_bg_color rgba(62, 62, 62, 1.00);
      @define-color popover_fg_color rgba(215, 211, 205, 1.00);

      @define-color shade_color rgba(0, 0, 0, 0.32);
      @define-color scrollbar_outline_color rgba(40, 40, 40, 0.50);

      @define-color accent_color rgba(146, 131, 116, 1.00);
      @define-color accent_bg_color rgba(146, 131, 116, 1.00);
      @define-color accent_fg_color rgba(0, 0, 0, 1.00);

      @define-color destructive_color rgba(234, 105, 98, 1.00);
      @define-color destructive_bg_color rgba(234, 105, 98, 1.00);
      @define-color destructive_fg_color rgba(0, 0, 0, 1.00);

      @define-color warning_color rgba(216, 166, 87, 1.00);
      @define-color warning_bg_color rgba(216, 166, 87, 1.00);
      @define-color warning_fg_color rgba(0, 0, 0, 1.00);

      @define-color success_color rgba(169, 182, 101, 1.00);
      @define-color success_bg_color rgba(169, 182, 101, 1.00);
      @define-color success_fg_color rgba(0, 0, 0, 1.00);

      @define-color error_color rgba(234, 105, 98, 1.00);
      @define-color error_bg_color rgba(234, 105, 98, 1.00);
      @define-color error_fg_color rgba(0, 0, 0, 1.00);

      @define-color blue_1 rgba(143, 192, 181, 1.00);
      @define-color blue_2 rgba(134, 183, 172, 1.00);
      @define-color blue_3 rgba(125, 174, 163, 1.00);
      @define-color blue_4 rgba(104, 152, 141, 1.00);
      @define-color blue_5 rgba(83, 130, 120, 1.00);

      @define-color green_1 rgba(185, 198, 117, 1.00);
      @define-color green_2 rgba(177, 190, 109, 1.00);
      @define-color green_3 rgba(169, 182, 101, 1.00);
      @define-color green_4 rgba(146, 158, 78, 1.00);
      @define-color green_5 rgba(124, 136, 54, 1.00);

      @define-color yellow_1 rgba(232, 182, 103, 1.00);
      @define-color yellow_2 rgba(224, 174, 95, 1.00);
      @define-color yellow_3 rgba(216, 166, 87, 1.00);
      @define-color yellow_4 rgba(191, 142, 62, 1.00);
      @define-color yellow_5 rgba(167, 119, 35, 1.00);

      @define-color red_1 rgba(255, 126, 117, 1.00);
      @define-color red_2 rgba(245, 115, 108, 1.00);
      @define-color red_3 rgba(234, 105, 98, 1.00);
      @define-color red_4 rgba(210, 84, 78, 1.00);
      @define-color red_5 rgba(187, 62, 59, 1.00);

      @define-color orange_1 rgba(250, 156, 96, 1.00);
      @define-color orange_2 rgba(241, 147, 87, 1.00);
      @define-color orange_3 rgba(231, 138, 78, 1.00);
      @define-color orange_4 rgba(206, 116, 54, 1.00);
      @define-color orange_5 rgba(182, 94, 28, 1.00);

      @define-color purple_1 rgba(186, 163, 218, 1.00);
      @define-color purple_2 rgba(177, 153, 208, 1.00);
      @define-color purple_3 rgba(167, 144, 198, 1.00);
      @define-color purple_4 rgba(146, 123, 176, 1.00);
      @define-color purple_5 rgba(125, 103, 154, 1.00);

      @define-color light_0 rgba(0, 0, 0, 1.00);
      @define-color light_1 rgba(10, 3, 0, 1.00);
      @define-color light_2 rgba(35, 25, 16, 1.00);
      @define-color light_3 rgba(63, 52, 42, 1.00);
      @define-color light_4 rgba(93, 81, 71, 1.00);

      @define-color dark_0 rgba(125, 112, 101, 1.00);
      @define-color dark_1 rgba(159, 145, 134, 1.00);
      @define-color dark_2 rgba(194, 180, 168, 1.00);
      @define-color dark_3 rgba(230, 215, 203, 1.00);
      @define-color dark_4 rgba(255, 255, 255, 1.00);
    '';

    # Ensure required fonts are available
    home.packages = with pkgs; [
      inter
      nerd-fonts.jetbrains-mono
      nerd-fonts.fira-code
    ];

    # Session environment variables for dark mode enforcement
    home.sessionVariables = mkIf (cfg.theme.variant == "dark") {
      # GTK dark mode enforcement
      GTK_THEME = "Gruvbox-Dark-Medium:dark";
      GTK_APPLICATION_PREFER_DARK_THEME = "1";

      # Cursor theme
      XCURSOR_THEME = "Bibata-Modern-Classic";
      XCURSOR_SIZE = "16";
    };

    # GNOME-specific theming via dconf (use mkForce to override Stylix)
    dconf.settings = mkIf cfg.theme.enable {
      "org/gnome/desktop/interface" = {
        gtk-theme = mkForce (if cfg.theme.variant == "dark" then "Gruvbox-Dark-Medium" else "Gruvbox-Light-BL");
        icon-theme = mkForce "Gruvbox-Material-Dark";
        cursor-theme = mkForce "Bibata-Modern-Classic";
        cursor-size = mkForce 16;
        font-name = mkForce "Inter 11";
        document-font-name = mkForce "Inter 11";
        monospace-font-name = mkForce "Adwaita Mono 11";
        color-scheme = mkForce (if cfg.theme.variant == "dark" then "prefer-dark" else "prefer-light");
      };

      "org/gnome/desktop/wm/preferences" = {
        titlebar-font = "Inter Bold 11";
      };

      # Terminal theming (GNOME Terminal)
      "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9" = {
        background-color = "#282828";
        foreground-color = "#ebdbb2";
        palette = [
          "#282828" # black
          "#cc241d" # red
          "#98971a" # green
          "#d79921" # yellow
          "#458588" # blue
          "#b16286" # magenta
          "#689d6a" # cyan
          "#a89984" # white
          "#928374" # bright black
          "#fb4934" # bright red
          "#b8bb26" # bright green
          "#fabd2f" # bright yellow
          "#83a598" # bright blue
          "#d3869b" # bright magenta
          "#8ec07c" # bright cyan
          "#ebdbb2" # bright white
        ];
        use-theme-colors = false;
        use-system-font = false;
        font = "Adwaita Mono 11";
        audible-bell = false;
        visual-bell = false;
      };

      # Set Gruvbox wallpaper if available (defaults - can be overridden by Stylix)
      "org/gnome/desktop/background" = {
        picture-uri = mkDefault "file://${pkgs.gruvbox-gtk-theme}/share/themes/Gruvbox-Dark-BL/wallpaper.jpg";
        picture-uri-dark = mkDefault "file://${pkgs.gruvbox-gtk-theme}/share/themes/Gruvbox-Dark-BL/wallpaper.jpg";
        picture-options = mkDefault "zoom";
        primary-color = mkDefault "#282828";
        secondary-color = mkDefault "#1d2021";
      };

      "org/gnome/desktop/screensaver" = {
        picture-uri = mkDefault "file://${pkgs.gruvbox-gtk-theme}/share/themes/Gruvbox-Dark-BL/wallpaper.jpg";
        primary-color = mkDefault "#282828";
        secondary-color = mkDefault "#1d2021";
      };
    };

    # Stylix integration for system-wide theming (disabled - wallpaper URL not found)
    # stylix = mkIf (hasAttr "stylix" config) {
    #   enable = true;
    #   base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-medium.yaml";
    #   image = pkgs.fetchurl {
    #     url = "https://raw.githubusercontent.com/lunik1/gruvbox-material-gtk/main/wallpapers/gruvbox-dark-rainbow.png";
    #     sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    #   };
    #
    #   fonts = {
    #     serif = {
    #       package = pkgs.inter;
    #       name = "Inter";
    #     };
    #     sansSerif = {
    #       package = pkgs.inter;
    #       name = "Inter";
    #     };
    #     monospace = {
    #       package = pkgs.nerd-fonts.jetbrains-mono;
    #       name = "JetBrainsMono Nerd Font";
    #     };
    #     emoji = {
    #       package = pkgs.noto-fonts-color-emoji;
    #       name = "Noto Color Emoji";
    #     };
    #   };
    # };

  };
}
