{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.desktop.gnome;
in
{
  config = mkIf (cfg.enable && cfg.theme.enable) {
    # GTK theming with Gruvbox colors
    gtk = {
      enable = true;

      theme = {
        package = mkDefault pkgs.gruvbox-gtk-theme;
        name = mkDefault (if cfg.theme.variant == "dark" then "Gruvbox-Dark" else "Gruvbox-Light");
      };

      iconTheme = {
        package = mkDefault pkgs.gruvbox-plus-icons;
        name = mkDefault "Gruvbox-Material-Dark";
      };

      cursorTheme = {
        package = mkDefault pkgs.bibata-cursors;
        name = mkDefault "Bibata-Modern-Classic";
        size = mkDefault 16;
      };

      font = {
        name = mkDefault "Inter";
        size = mkDefault 11;
      };

      gtk3.extraConfig = {
        gtk-application-prefer-dark-theme = cfg.theme.variant == "dark";
      };

      gtk4.extraConfig = {
        gtk-application-prefer-dark-theme = cfg.theme.variant == "dark";
      };
    };

    # Prevent Home Manager from writing gtk.css files
    # COSMIC desktop generates these at runtime (~/.config/gtk-{3,4}.0/gtk.css)
    # and conflicts with declaratively managed files
    xdg.configFile."gtk-3.0/gtk.css".enable = false;
    xdg.configFile."gtk-4.0/gtk.css".enable = false;

    # Modern Stylix GTK CSS customization (replaces deprecated gtk3/gtk4.extraCss)
    # Optional: Enable for custom CSS overrides
    # stylix.targets.gtk.extraCss = ''
    #   /* GENERATED BY COSMIC */
    #   @define-color window_bg_color rgba(40, 40, 40, 1.00);
    #   @define-color window_fg_color rgba(255, 251, 245, 1.00);
    #   ... (CSS content preserved in git history)
    # '';

    # Ensure required fonts are available
    home.packages = with pkgs; [
      inter
      nerd-fonts.jetbrains-mono
      nerd-fonts.fira-code
    ];

    # Session environment variables for dark mode enforcement
    home.sessionVariables = mkIf (cfg.theme.variant == "dark") {
      # GTK dark mode enforcement
      GTK_THEME = "Gruvbox-Dark:dark";
      GTK_APPLICATION_PREFER_DARK_THEME = "1";

      # Cursor theme
      XCURSOR_THEME = "Bibata-Modern-Classic";
      XCURSOR_SIZE = "16";
    };

    # GNOME-specific theming via dconf (use mkForce to override Stylix)
    dconf.settings = mkIf cfg.theme.enable {
      "org/gnome/desktop/interface" = {
        gtk-theme = mkForce (if cfg.theme.variant == "dark" then "Gruvbox-Dark" else "Gruvbox-Light");
        icon-theme = mkForce "Gruvbox-Material-Dark";
        cursor-theme = mkForce "Bibata-Modern-Classic";
        cursor-size = mkForce 16;
        font-name = mkForce "Inter 11";
        document-font-name = mkForce "Inter 11";
        monospace-font-name = mkForce "Adwaita Mono 11";
        color-scheme = mkForce (if cfg.theme.variant == "dark" then "prefer-dark" else "prefer-light");
      };

      "org/gnome/desktop/wm/preferences" = {
        titlebar-font = "Inter Bold 11";
      };

      # Terminal theming (GNOME Terminal)
      "org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9" = {
        background-color = "#282828";
        foreground-color = "#ebdbb2";
        palette = [
          "#282828" # black
          "#cc241d" # red
          "#98971a" # green
          "#d79921" # yellow
          "#458588" # blue
          "#b16286" # magenta
          "#689d6a" # cyan
          "#a89984" # white
          "#928374" # bright black
          "#fb4934" # bright red
          "#b8bb26" # bright green
          "#fabd2f" # bright yellow
          "#83a598" # bright blue
          "#d3869b" # bright magenta
          "#8ec07c" # bright cyan
          "#ebdbb2" # bright white
        ];
        use-theme-colors = false;
        use-system-font = false;
        font = "Adwaita Mono 11";
        audible-bell = false;
        visual-bell = false;
      };

      # Set Gruvbox wallpaper if available (defaults - can be overridden by Stylix)
      "org/gnome/desktop/background" = {
        picture-options = mkDefault "zoom";
        primary-color = mkDefault "#282828";
        secondary-color = mkDefault "#1d2021";
      };

      "org/gnome/desktop/screensaver" = {
        primary-color = mkDefault "#282828";
        secondary-color = mkDefault "#1d2021";
      };
    };

    # Stylix integration for system-wide theming (disabled - wallpaper URL not found)
    # stylix = mkIf (hasAttr "stylix" config) {
    #   enable = true;
    #   base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-medium.yaml";
    #   image = pkgs.fetchurl {
    #     url = "https://raw.githubusercontent.com/lunik1/gruvbox-material-gtk/main/wallpapers/gruvbox-dark-rainbow.png";
    #     sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    #   };
    #
    #   fonts = {
    #     serif = {
    #       package = pkgs.inter;
    #       name = "Inter";
    #     };
    #     sansSerif = {
    #       package = pkgs.inter;
    #       name = "Inter";
    #     };
    #     monospace = {
    #       package = pkgs.nerd-fonts.jetbrains-mono;
    #       name = "JetBrainsMono Nerd Font";
    #     };
    #     emoji = {
    #       package = pkgs.noto-fonts-color-emoji;
    #       name = "Noto Color Emoji";
    #     };
    #   };
    # };

  };
}

