{ config
, lib
, pkgs
, pkgs-stable
, ...
}:
with lib; let
  cfg = config.features.email;
  emailCfg = cfg.neomutt;
in
{
  imports = [
    ./accounts.nix
    ./theme.nix
  ];

  config = mkIf (cfg.enable && emailCfg.enable) {
    # Create neomutt configuration directory
    environment.etc."neomutt/neomuttrc" = {
      text = ''
        # Basic NeoMutt Configuration
        # Generated by NixOS Email Module

        # Basic settings
        set mail_check = 0
        set imap_keepalive = 300
        set imap_idle
        unset mark_old
        set beep_new

        # Display settings
        set sort = threads
        set sort_aux = reverse-date-received
        set date_format = "%Y-%m-%d %H:%M"
        set index_format = "%2C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"

        # Composition settings
        set editor = "nvim"
        set charset = "utf-8"
        set send_charset = "utf-8"

        # Security settings
        set ssl_starttls = yes
        set ssl_force_tls = yes

        # HTML email handling
        set mailcap_path = /etc/neomutt/mailcap
        auto_view text/html
        alternative_order text/plain text/enriched text/html

        # Basic folder setup (will be expanded with account-specific configs)
        set folder = "~/Mail"
        set spoolfile = "+INBOX"
        set mbox = "+Archive"
        set postponed = "+Drafts"
        set record = "+Sent"

        # Basic key bindings
        bind index,pager \Ck sidebar-prev
        bind index,pager \Cj sidebar-next
        bind index,pager \Co sidebar-open
        bind index,pager \Cp sidebar-toggle

        # Account switching (will be configured in accounts.nix)
        macro index <f2> '<sync-mailbox><enter-command>source ~/.config/neomutt/accounts/freundcloud<enter><change-folder>!<enter>'
        macro index <f3> '<sync-mailbox><enter-command>source ~/.config/neomutt/accounts/gmail<enter><change-folder>!<enter>'

        # Include theme
        source /etc/neomutt/colors-gruvbox

        # Include account-specific configurations
        source ~/.config/neomutt/accounts/freundcloud
      '';
      mode = "0644";
    };

    # Create mailcap for HTML handling
    environment.etc."neomutt/mailcap" = {
      text = ''
        # HTML email handling
        text/html; ${pkgs.w3m}/bin/w3m -I %{charset} -T text/html; copiousoutput;
        text/html; ${pkgs.w3m}/bin/w3m -I %{charset} -T text/html -dump %s; nametemplate=%s.html; copiousoutput;

        # PDF handling
        application/pdf; ${pkgs.zathura}/bin/zathura %s;

        # Image handling
        image/*; ${pkgs.chafa}/bin/chafa --size=80x24 %s; copiousoutput;

        # Other document types
        application/msword; ${pkgs-stable.libreoffice}/bin/libreoffice --writer %s;
        application/vnd.openxmlformats-officedocument.wordprocessingml.document; ${pkgs-stable.libreoffice}/bin/libreoffice --writer %s;
      '';
      mode = "0644";
    };

    # Ensure mail directory exists for users
    system.activationScripts.emailDirectories = ''
      # Create mail directories for known users
      for user in olafkfreund; do
        if [ -d "/home/$user" ]; then
          mkdir -p "/home/$user/Mail"
          mkdir -p "/home/$user/.config/neomutt/accounts"
          chown -R "$user:users" "/home/$user/Mail" "/home/$user/.config/neomutt" 2>/dev/null || true
        fi
      done
    '';
  };
}
