# Google Antigravity — declarative config bridge
#
# Antigravity (the `agy` CLI + IDE) keeps most of its config under ~/.gemini/.
# This module makes the *user-authored, reproducible* pieces declarative while
# leaving agent-managed runtime state alone:
#
#   - ~/.gemini/AGENTS.md      → global rules, now generated by
#                                agent-rules.nix (shared with ~/.codex, #1832).
#   - ~/.gemini/config/mcp_config.json → ADDITIVELY synced: a small set of
#                                clean, secret-free stdio MCP servers is merged
#                                in, but every server the user already has
#                                ALWAYS wins. Never removes or overwrites.
#
# Deliberately NOT managed (agent/runtime state — would break Antigravity):
#   - ~/.gemini/GEMINI.md       (agent auto-memory — Antigravity writes it)
#   - ~/.gemini/oauth_creds.json, state.json, brain/, history, etc.
#
# Note: Antigravity is OAuth-only (no BYOK), so API keys are NOT declarable.
{ config
, lib
, pkgs
, osConfig ? null
, ...
}:
let
  cfg = config.programs.antigravityConfig;

  geminiDir = "${config.home.homeDirectory}/.gemini";

  # Gated the same way as in claude-code-mcp.nix: the package ships only with
  # profile.nix (p620, razer) while this module is evaluated for every host.
  notebooklmEnabled =
    if osConfig != null
    then (osConfig.features.ai.mcp.notebooklm.enable or false)
    else false;

  # GitHub PAT — sourced from agenix at runtime instead of sitting in plaintext
  # in mcp_config.json. Mirrors the Claude Code github-mcp wrapper. Only applied
  # if the host actually decrypts api-github-token.
  ghToken =
    if osConfig != null
    then (osConfig.age.secrets."api-github-token" or null)
    else null;

  # github-mcp-server only reads GITHUB_PERSONAL_ACCESS_TOKEN (not
  # GITHUB_TOKEN_FILE) and requires the `stdio` subcommand to start.
  githubWrapper = pkgs.writeShellScript "antigravity-github-mcp" ''
    export GITHUB_PERSONAL_ACCESS_TOKEN="$(cat ${if ghToken != null then ghToken.path else "/dev/null"})"
    exec ${pkgs.github-mcp-server}/bin/github-mcp-server stdio
  '';

  # Override layer (mine wins): replaces any plaintext-token github-mcp-server
  # entry with the agenix-backed wrapper. Empty if the secret isn't available
  # or the feature is off — the existing entry is then left untouched.
  overrideMcpServers = lib.optionalAttrs (cfg.secureGithubMcp && ghToken != null) {
    github-mcp-server = {
      command = toString githubWrapper;
      args = [ ];
    };
  };

  overrideMcpFile = (pkgs.formats.json { }).generate "antigravity-override-mcp.json" {
    mcpServers = overrideMcpServers;
  };

  # Clean, secret-free stdio MCP servers to share into Antigravity. These map
  # 1:1 onto Antigravity's command/args/env schema. SSE/secret-bound servers
  # from the Claude set are intentionally excluded (different transport / would
  # leak credentials into a plaintext file).
  sharedMcpServers = {
    context7 = {
      command = "${pkgs.nodejs}/bin/npx";
      args = [ "-y" "@upstash/context7-mcp@latest" ];
    };
    sequential-thinking = {
      command = "${pkgs.nodejs}/bin/npx";
      args = [ "-y" "@modelcontextprotocol/server-sequential-thinking" ];
    };
  }
  # NotebookLM, on the hosts that ship it. Secret-free in the file sense: the
  # Google session cookie lives in ~/.notebooklm-mcp-cli/, not in any argument
  # or env var here, so this stays safe to write into a plaintext config.
  // lib.optionalAttrs notebooklmEnabled {
    notebooklm = {
      command = "${pkgs.customPkgs.notebooklm-mcp-cli}/bin/notebooklm-mcp";
      args = [ ];
    };
  };

  sharedMcpFile = (pkgs.formats.json { }).generate "antigravity-shared-mcp.json" {
    mcpServers = sharedMcpServers;
  };

  # The PreToolUse entry that wires agy's hook system to the coder guard
  # adapter installed at /etc/antigravity/hooks/coder-guard (#2087). The
  # command is a shell gate, not the bare path: hosts that don't have the
  # /etc file yet (p510, or razer in the seconds before it's deployed, while
  # Syncthing has already carried this hooks.json entry over) must not have
  # every agy tool call fail just because the file is missing, and a plain
  # agy session (AGY_CODER unset) must never touch the guard at all. So the
  # gate itself decides "allow" before the guard file is ever referenced,
  # and only execs it once AGY_CODER=1.
  coderGuardHookEntry = (pkgs.formats.json { }).generate "antigravity-coder-guard-hook.json" {
    "coder-guard" = {
      PreToolUse = [
        {
          matcher = "*";
          hooks = [
            {
              type = "command";
              command = "/bin/sh -c '[ \"\${AGY_CODER:-}\" = 1 ] || { echo \"{\\\"decision\\\":\\\"allow\\\"}\"; exit 0; }; exec /etc/antigravity/hooks/coder-guard'";
              timeout = 10;
            }
          ];
        }
      ];
    };
  };

  # Launcher for a write-access agy session on an approved plan (#2087). Fails
  # closed: refuses to run unless the guard adapter is installed and hooks.json
  # actually registers it, so a session can never end up with write access and
  # no guard because of drift between the /etc file and the synced hooks.json.
  agyImplement = pkgs.writeShellScriptBin "agy-implement" ''
    guard="/etc/antigravity/hooks/coder-guard"
    hooks="${geminiDir}/config/hooks.json"

    if [ ! -x "$guard" ]; then
      echo "agy-implement: $guard is missing or not executable -- refusing to run with write access (#2087)." >&2
      exit 1
    fi

    if ! ${pkgs.jq}/bin/jq -e \
        '[."coder-guard".PreToolUse[]?.hooks[]?.command // empty] | any(contains("/etc/antigravity/hooks/coder-guard"))' \
        "$hooks" >/dev/null 2>&1; then
      echo "agy-implement: $hooks has no coder-guard hook registered -- refusing to run with write access (#2087)." >&2
      exit 1
    fi

    AGY_CODER=1 exec agy --mode accept-edits --model gemini-3.8-flash-medium --sandbox "$@"
  '';

in
{
  options.programs.antigravityConfig = {
    enable = lib.mkEnableOption "declarative Google Antigravity config bridge" // {
      default = true;
    };

    syncMcp = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Additively merge a small set of clean, secret-free stdio MCP servers
        into ~/.gemini/config/mcp_config.json. Existing servers always win;
        this only fills gaps and never removes anything.
      '';
    };

    secureGithubMcp = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Replace any github-mcp-server entry in mcp_config.json (which Antigravity
        stores with the PAT in plaintext) with an agenix-backed wrapper that
        sources the token from api-github-token at runtime. No-op if the secret
        isn't decrypted on this host.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Global rules (~/.gemini/AGENTS.md) come from agent-rules.nix (#1832).
    # GEMINI.md stays agent-managed.

    home.packages = [ agyImplement ];

    home.activation.antigravityCoderGuardHook = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      hooksfile="${geminiDir}/config/hooks.json"
      entry="${coderGuardHookEntry}"
      mkdir -p "${geminiDir}/config"

      if [ ! -f "$hooksfile" ]; then
        # Write via a temp file so $DRY_RUN_CMD (set to "echo" on a dry run)
        # actually stops the write -- $DRY_RUN_CMD cmd > file still performs
        # the redirection regardless of which command runs, so the publish
        # step must be a plain file operation, never end in `> "$hooksfile"`.
        tmp=$(mktemp)
        ${pkgs.coreutils}/bin/cat "$entry" > "$tmp"
        $DRY_RUN_CMD mv "$tmp" "$hooksfile"
        $DRY_RUN_CMD echo "Antigravity: seeded hooks.json with the coder guard (#2087)"
      elif ${pkgs.jq}/bin/jq -e 'type == "object"' "$hooksfile" >/dev/null 2>&1; then
        if ${pkgs.jq}/bin/jq -e '."coder-guard"' "$hooksfile" >/dev/null 2>&1; then
          $DRY_RUN_CMD echo "Antigravity: coder guard already registered in hooks.json"
        else
          tmp=$(mktemp)
          ${pkgs.jq}/bin/jq -s '.[0] + .[1]' "$hooksfile" "$entry" > "$tmp"
          $DRY_RUN_CMD mv "$tmp" "$hooksfile"
          $DRY_RUN_CMD echo "Antigravity: added the coder guard to hooks.json (#2087)"
        fi
      else
        $DRY_RUN_CMD echo "Antigravity: hooks.json is not a JSON object -- left untouched (#2087)"
      fi
    '';

    home.activation.antigravityMcpSync = lib.mkIf cfg.syncMcp (
      lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        cfgfile="${geminiDir}/config/mcp_config.json"
        shared="${sharedMcpFile}"
        override="${overrideMcpFile}"
        mkdir -p "$(dirname "$cfgfile")"

        if [ ! -f "$cfgfile" ]; then
          # Seed = shared servers, with the secure github override applied.
          if seeded=$(${pkgs.jq}/bin/jq -s \
              '.[0] + {mcpServers: ((.[0].mcpServers // {}) + (.[1].mcpServers // {}))}' \
              "$shared" "$override" 2>/dev/null); then
            $DRY_RUN_CMD printf '%s\n' "$seeded" > "$cfgfile"
            $DRY_RUN_CMD chmod 0644 "$cfgfile"
            $DRY_RUN_CMD echo "Antigravity: seeded mcp_config.json (shared + secure github)"
          fi
        elif merged=$(${pkgs.jq}/bin/jq -s \
            '.[1] + {mcpServers: ((.[0].mcpServers // {}) + (.[1].mcpServers // {}) + (.[2].mcpServers // {}))}' \
            "$shared" "$cfgfile" "$override" 2>/dev/null); then
          # Precedence: override (.[2]) > existing (.[1]) > shared (.[0]).
          # Existing servers preserved; gaps filled by shared; github-mcp-server
          # replaced by the agenix-backed wrapper (drops the plaintext token).
          $DRY_RUN_CMD printf '%s\n' "$merged" > "$cfgfile"
          $DRY_RUN_CMD echo "Antigravity: synced MCP (existing preserved, github secured)"
        else
          $DRY_RUN_CMD echo "Antigravity: mcp_config.json not valid JSON — left untouched"
        fi
      ''
    );
  };
}
