{ config, lib, pkgs, ... }:

let
  inherit (lib) mkIf mkEnableOption;
  inherit (config.lib.stylix) colors;
  cfg = config.programs.claude-powerline;

  # Truecolor SGR straight from the active base16 scheme. The statusline used
  # to hardcode ANSI-256 approximations, which drifted from every
  # other surface the moment the scheme changed — and 256-colour indices cannot
  # express the palette exactly anyway.
  sgr = layer: name: "\\e[${layer};2;${colors."${name}-rgb-r"};${colors."${name}-rgb-g"};${colors."${name}-rgb-b"}m";
  fg = sgr "38";
  bg = sgr "48";
in
{
  options.programs.claude-powerline = {
    enable = mkEnableOption "Claude Powerline statusline themed from the active base16 scheme";
  };

  config = mkIf cfg.enable {
    # ~/.claude/settings.json is NOT managed by Home Manager — it is
    # syncthing-synced and holds runtime plugin state. It points at
    # statusline-alien-hud.sh below; that wiring is done once, by hand.
    #
    # An @owloops/claude-powerline npx wrapper used to be generated here too,
    # but nothing ever referenced it: settings.json has always pointed at the
    # script below. It was also the wrong tool for this repo — it ran
    # `npx -y @owloops/claude-powerline@latest` on *every* statusline render,
    # i.e. an unpinned network fetch in the hot path of a NixOS config, and it
    # rendered no hostname segment (the one thing that matters most across
    # p620/razer/p510). Removed in #1159 along with its theme file and
    # CLAUDE_POWERLINE_CONFIG env var.

    home = {
      # Statusline script — mirrors your Starship prompt layout:
      # OS icon · hostname · user · dir · shell · git branch/status · model · context
      #
      # ~/.claude/settings.json points at this exact path. That file is
      # syncthing-synced and hand-maintained (NOT Home Manager's), so renaming
      # this script means editing settings.json too — once, since syncthing
      # propagates it to the other hosts.
      file.".claude/statusline-alien-hud.sh" = {
        executable = true;
        text = ''
          #!/usr/bin/env bash
          # Claude Code status line — Alien HUD (base16, generated by Nix)
          # Mirrors Starship prompt: OS  hostname  user  dir  zsh  git  model  ctx

          # Alien HUD, generated from the base16 scheme (assets/themes/alien-hud.yaml)
          HUD_BG1="${bg "base01"}"    # panel fill
          HUD_BG2="${bg "base02"}"    # selection fill
          HUD_YELLOW="${fg "base0A"}" # caution
          HUD_ORANGE="${fg "base09"}" # bar-graph amber
          HUD_GREEN="${fg "base0B"}"  # phosphor green
          HUD_BLUE="${fg "base0D"}"
          HUD_AQUA="${fg "base0C"}"   # readouts
          HUD_RED="${fg "base08"}"    # alarm
          HUD_PURPLE="${fg "base0E"}"
          HUD_FG0="${fg "base07"}"    # brightest plate cream
          HUD_FG2="${fg "base04"}"    # dim label text
          RESET="\e[0m"
          BOLD="\e[1m"

          input=$(cat)

          cwd=$(echo "$input"          | ${pkgs.jq}/bin/jq -r '.cwd // empty')
          model=$(echo "$input"        | ${pkgs.jq}/bin/jq -r '.model.display_name // empty')
          session=$(echo "$input"      | ${pkgs.jq}/bin/jq -r '.session_name // empty')
          used_pct=$(echo "$input"     | ${pkgs.jq}/bin/jq -r '.context_window.used_percentage // empty')
          vim_mode=$(echo "$input"     | ${pkgs.jq}/bin/jq -r '.vim.mode // empty')
          output_style=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.output_style.name // empty')
          five_h=$(echo "$input"       | ${pkgs.jq}/bin/jq -r '.rate_limits.five_hour.used_percentage // empty')
          seven_d=$(echo "$input"      | ${pkgs.jq}/bin/jq -r '.rate_limits.seven_day.used_percentage // empty')
          git_worktree=$(echo "$input" | ${pkgs.jq}/bin/jq -r '.workspace.git_worktree // empty')
          repo_name=$(echo "$input"    | ${pkgs.jq}/bin/jq -r '.workspace.repo | if . then .owner + "/" + .name else empty end')
          pr_num=$(echo "$input"       | ${pkgs.jq}/bin/jq -r '.pr.number // empty')
          pr_state=$(echo "$input"     | ${pkgs.jq}/bin/jq -r '.pr.review_state // empty')
          effort=$(echo "$input"       | ${pkgs.jq}/bin/jq -r '.effort.level // empty')

          segments=""

          # NixOS OS icon — matches starship [os] NixOS = " "
          segments+="''${HUD_FG0}  ''${RESET}"

          # Hostname — matches starship [hostname] style=bold fg:color_purple
          hostname_short=$(${pkgs.hostname}/bin/hostname -s 2>/dev/null)
          if [ -n "$hostname_short" ]; then
            segments+="''${HUD_BG1}''${HUD_PURPLE}''${BOLD} ''${hostname_short} ''${RESET}"
          fi

          # Username — matches starship [username] aliases olafkfreund→olaf, style=bold fg:color_green
          whoami_out=$(${pkgs.coreutils}/bin/whoami 2>/dev/null)
          if [ -n "$whoami_out" ]; then
            [ "$whoami_out" = "olafkfreund" ] && display_user="olaf" || display_user="$whoami_out"
            segments+="''${HUD_BG1}''${HUD_GREEN}''${BOLD} ''${display_user} ''${RESET}"
          fi

          # CWD — matches starship [directory] style=bold fg:color_blue, truncation_length=2, home_symbol=~
          if [ -n "$cwd" ]; then
            short_cwd="''${cwd/#$HOME/~}"
            depth=$(echo "$short_cwd" | tr -cd '/' | wc -c)
            if [ "$depth" -gt 2 ]; then
              short_cwd="…/$(echo "$short_cwd" | rev | cut -d'/' -f1-2 | rev)"
            fi
            segments+="''${HUD_BG1}''${HUD_BLUE}''${BOLD} ''${short_cwd} ''${RESET}"
          fi

          # Shell indicator — matches starship [shell] zsh_indicator="zsh", style=fg:color_aqua
          segments+="''${HUD_AQUA} zsh ''${RESET}"

          # Git branch — matches starship [git_branch] symbol=" ", style=bold fg:color_purple
          git_branch=""
          if [ -n "$cwd" ]; then
            git_branch=$(${pkgs.git}/bin/git -C "$cwd" symbolic-ref --short HEAD 2>/dev/null \
                         || ${pkgs.git}/bin/git -C "$cwd" rev-parse --short HEAD 2>/dev/null)
          fi
          if [ -n "$git_branch" ]; then
            git_status_flags=""
            if [ -n "$cwd" ]; then
              modified=$(${pkgs.git}/bin/git -C "$cwd" status --porcelain 2>/dev/null | grep -c '^ M\|^M ' || true)
              untracked=$(${pkgs.git}/bin/git -C "$cwd" status --porcelain 2>/dev/null | grep -c '^??' || true)
              staged=$(${pkgs.git}/bin/git -C "$cwd" status --porcelain 2>/dev/null | grep -c '^[MADRC]' || true)
              [ "$modified" -gt 0 ] 2>/dev/null   && git_status_flags+="!"
              [ "$untracked" -gt 0 ] 2>/dev/null  && git_status_flags+="?"
              [ "$staged" -gt 0 ] 2>/dev/null     && git_status_flags+="+''${staged}"
            fi
            git_label=" ''${git_branch}"
            [ -n "$git_status_flags" ] && git_label+=" ''${git_status_flags}"
            segments+="''${HUD_BG2}''${HUD_PURPLE}''${BOLD}''${git_label} ''${RESET}"
          fi

          # Git worktree (when in a linked worktree)
          if [ -n "$git_worktree" ]; then
            segments+="''${HUD_BG2}''${HUD_AQUA} worktree:''${git_worktree} ''${RESET}"
          fi

          # Repo (owner/name)
          if [ -n "$repo_name" ]; then
            segments+="''${HUD_BG2}''${HUD_FG2} ''${repo_name} ''${RESET}"
          fi

          # PR badge
          if [ -n "$pr_num" ]; then
            case "$pr_state" in
              approved)          pr_color="''${HUD_GREEN}"  ; pr_icon="" ;;
              changes_requested) pr_color="''${HUD_RED}"    ; pr_icon="" ;;
              draft)             pr_color="''${HUD_FG2}"    ; pr_icon="" ;;
              *)                 pr_color="''${HUD_YELLOW}" ; pr_icon="" ;;
            esac
            segments+="''${HUD_BG1}''${pr_color} ''${pr_icon}#''${pr_num} ''${RESET}"
          fi

          # Model — yellow for prominence
          if [ -n "$model" ]; then
            segments+="''${HUD_BG2}''${HUD_YELLOW} ''${model} ''${RESET}"
          fi

          # Session name (orange)
          if [ -n "$session" ]; then
            segments+="''${HUD_BG1}''${HUD_ORANGE} ''${session} ''${RESET}"
          fi

          # Effort level (when reasoning model is active)
          if [ -n "$effort" ]; then
            case "$effort" in
              low)       eff_color="''${HUD_FG2}" ;;
              high)      eff_color="''${HUD_YELLOW}" ;;
              xhigh|max) eff_color="''${HUD_RED}" ;;
              *)         eff_color="''${HUD_AQUA}" ;;
            esac
            segments+="''${HUD_BG2}''${eff_color} effort:''${effort} ''${RESET}"
          fi

          # Output style (purple) — only when non-default
          if [ -n "$output_style" ] && [ "$output_style" != "default" ] && [ "$output_style" != "Default" ]; then
            segments+="''${HUD_BG2}''${HUD_PURPLE} ''${output_style} ''${RESET}"
          fi

          # Vim mode — matches starship [character] vimcmd symbols
          if [ -n "$vim_mode" ]; then
            case "$vim_mode" in
              INSERT)        segments+="''${HUD_BG1}''${HUD_GREEN}''${BOLD} INSERT ''${RESET}" ;;
              NORMAL)        segments+="''${HUD_BG1}''${HUD_BLUE}''${BOLD} NORMAL ''${RESET}" ;;
              VISUAL)        segments+="''${HUD_BG1}''${HUD_PURPLE}''${BOLD} VISUAL ''${RESET}" ;;
              "VISUAL LINE") segments+="''${HUD_BG1}''${HUD_PURPLE}''${BOLD} V-LINE ''${RESET}" ;;
              *)             segments+="''${HUD_BG1}''${HUD_FG2} ''${vim_mode} ''${RESET}" ;;
            esac
          fi

          # Context window usage — color-coded green/yellow/red
          if [ -n "$used_pct" ]; then
            used_int=$(printf '%.0f' "$used_pct")
            if   [ "$used_int" -ge 80 ]; then ctx_color="''${HUD_RED}"
            elif [ "$used_int" -ge 50 ]; then ctx_color="''${HUD_YELLOW}"
            else                               ctx_color="''${HUD_GREEN}"
            fi
            segments+="''${HUD_BG2}''${ctx_color} ctx:''${used_int}% ''${RESET}"
          fi

          # Rate limits (subscribers only)
          rate_seg=""
          if [ -n "$five_h" ]; then
            five_int=$(printf '%.0f' "$five_h")
            [ "$five_int" -ge 80 ] && rl_color="''${HUD_RED}" || rl_color="''${HUD_ORANGE}"
            rate_seg+="''${rl_color}5h:''${five_int}%''${RESET}"
          fi
          if [ -n "$seven_d" ]; then
            seven_int=$(printf '%.0f' "$seven_d")
            [ "$seven_int" -ge 80 ] && rl_color="''${HUD_RED}" || rl_color="''${HUD_FG2}"
            [ -n "$rate_seg" ] && rate_seg+=" "
            rate_seg+="''${rl_color}7d:''${seven_int}%''${RESET}"
          fi
          if [ -n "$rate_seg" ]; then
            segments+="''${HUD_BG1} ''${rate_seg} ''${RESET}"
          fi

          printf "%b" "''${segments}"
        '';
      };

    };
  };
}
