#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. There is a link to this file in ~/.xprofile
# because that file is run automatically if someone uses a display manager
# (login screen) and so they are needed there. To prevent doubling up commands,
# I source them here with the line below.

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi
# Activate dbus variables
# dbus-update-activation-environment --all
# dbus-launch ssh-agent
xrdb ~/.Xresources_dwm
exec dwm &
# exec slstatus &
exec st &
exec picom &
# exec gnome-keyring-daemon --start --components=secrets &
# exec polkit-kde-authentication-agent-1 &
# exec kdeconnectd &
# exec kdeconnect-indicator &
# exec dbus-update-activation-environment --systemd --all &
# exec polkit-agent-helper-1 &
# exec gsettings set org.gnome.desktop.interface cursor-theme "Bibata-Modern-Ice" &
# exec gsettings set org.gnome.desktop.interface icon-theme "Gruvbox-Plus-Dark" &
# exec gsettings set org.gnome.desktop.interface gtk-theme "Gruvbox-Dark-BL-LB" &
# exec kdeconnect-cli --refresh &
# exec playerctld daemon &
# exec nm-applet --indicator &
# exec blueman-applet &
