nix-build-container-img:
  nix build .#nixosConfigurations.container.config.system.build.squashfs --print-out-paths

nix-build-container-metadata:
  nix build .#nixosConfigurations.container.config.system.build.metadata --print-out-paths

nix-build-vm-img:
  nix build .#nixosConfigurations.vm.config.system.build.qemuImage --print-out-paths

nix-build-vm-metadata:
  nix build .#nixosConfigurations.vm.config.system.build.metadata --print-out-paths

default:
  cat README.md
