k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: internal
  currentCluster: internalCluster
  keepMissingClusters: false
  clusters:
    internalCluster:
      namespace:
        active: dc-tanxg
        lockFavorites: false
        favorites:
        - all
        - dc-tanxg-ui
        - dc-tanxc-ui
        - dc-tanxc
        - dc-tanxg
        - fast-track-ui
        - fast-track-institution-ui
        - corda
        - keycloak-cbdc
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-olafkfreund
  disablePodCounting: false
