# Kometa (was Plex Meta Manager) — collections + metadata + posters for Plex.
#
# Runs as a podman OCI container on p510 sharing the host network namespace
# so it can reach localhost:32400 (Plex) directly. Container is always-on;
# Kometa's internal scheduler fires per the `schedule:` key in config.yml.
#
# Phase 1a (this commit): dry-run mode + IMDb Top 250 only. Once the
# dry-run output looks right, flip `dry_run: false` in
# modules/services/kometa/config.yml and redeploy.
#
# Pattern mirrors modules/services/skill-pool.nix (oci-containers + podman).
#
# Config flow:
#   modules/services/kometa/config.yml  <-- repo source of truth; contains
#                                           ${TMDB_API_KEY} + ${PLEX_TOKEN}
#                                           shell-style placeholders.
#   kometa-config-render.service        <-- systemd oneshot; envsubst's
#                                           the template into
#                                           /var/lib/kometa/config.yml
#                                           with agenix-provided values.
#   podman-kometa.service               <-- depends on the oneshot; mounts
#                                           /var/lib/kometa as /config.
{ config
, lib
, pkgs
, ...
}:
let
  cfg = config.features.kometa;
  # Template lives in repo; the oneshot envsubst's it at activation time.
  configTemplate = ./config.yml;
in
{
  options.features.kometa = {
    enable = lib.mkEnableOption "Kometa (Plex Meta Manager)";
  };

  config = lib.mkIf cfg.enable {
    age.secrets."kometa-env" = {
      file = ../../../secrets/kometa-env.age;
      mode = "0400";
    };

    # Mirror skill-pool.nix: container infrastructure declared per-host
    # rather than globally; this also picks up podman as the backend.
    virtualisation.podman.enable = lib.mkDefault true;

    virtualisation.oci-containers = {
      backend = "podman";

      containers."kometa" = {
        image = "kometateam/kometa:latest";
        autoStart = true;
        environmentFiles = [ config.age.secrets."kometa-env".path ];
        environment = {
          # Source of truth is the repo template; rendered config.yml is
          # regenerated by kometa-config-render.service on every activation.
          # Tell Kometa not to mutate it at runtime.
          KOMETA_READ_ONLY_CONFIG = "true";
        };
        volumes = [
          # /config is Kometa's working dir. config.yml is rendered into
          # /var/lib/kometa/config.yml by kometa-config-render below.
          "/var/lib/kometa:/config"
        ];
        extraOptions = [
          # Host network: lets Kometa reach Plex at localhost:32400 + any
          # *arr service on its loopback port without container DNS
          # gymnastics. Acceptable isolation tradeoff: Kometa only makes
          # outbound calls (Plex API + TMDB), no inbound surface.
          "--network=host"
        ];
      };
    };

    systemd.tmpfiles.rules = [
      "d /var/lib/kometa 0755 root root - -"
      "d /var/lib/kometa/assets 0755 root root - -"
      "d /var/lib/kometa/logs 0755 root root - -"
    ];

    # Render the config template into /var/lib/kometa/config.yml on every
    # activation, substituting agenix-provided values for ${TMDB_API_KEY}
    # and ${PLEX_TOKEN}. Runs before podman-kometa so the container always
    # finds a fresh, secret-populated config when it starts.
    systemd.services.kometa-config-render = {
      description = "Render Kometa config.yml from template + agenix secrets";
      wantedBy = [ "podman-kometa.service" ];
      before = [ "podman-kometa.service" ];
      requires = [ "agenix.service" ];
      after = [ "agenix.service" ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = false;
        EnvironmentFile = config.age.secrets."kometa-env".path;
        ExecStart = pkgs.writeShellScript "kometa-render-config" ''
          set -euo pipefail
          ${pkgs.gettext}/bin/envsubst < ${configTemplate} > /var/lib/kometa/config.yml.new
          mv -f /var/lib/kometa/config.yml.new /var/lib/kometa/config.yml
          chmod 0640 /var/lib/kometa/config.yml
        '';
      };
    };

    # Make sure podman-kometa restarts when the rendered config changes.
    systemd.services.podman-kometa = {
      after = [ "kometa-config-render.service" ];
      requires = [ "kometa-config-render.service" ];
    };
  };
}
