# Claude Desktop MCP Configuration
# Automatically generates claude_desktop_config.json for MCP servers
# Follows docs/NIXOS-ANTI-PATTERNS.md security patterns
{ config, lib, pkgs, osConfig, ... }:
let
  # Access system-level MCP configuration via osConfig
  mcpCfg = osConfig.features.ai.mcp or { };
  enabled = mcpCfg.enable or false;
  obsidianEnabled = mcpCfg.obsidian.enable or false;
in
{
  config = lib.mkIf enabled {
    # Claude Desktop MCP configuration file
    # Location: ~/.config/Claude/claude_desktop_config.json
    xdg.configFile."Claude/claude_desktop_config.json" = {
      text = builtins.toJSON {
        mcpServers =
          # Always enabled MCP servers
          {
            # NixOS MCP server
            nixos = {
              command = "mcp-nixos";
              args = [ ];
              description = "NixOS package and option queries";
            };

            # Context7 for up-to-date library documentation
            context7 = {
              type = "stdio";
              command = "${pkgs.nodejs}/bin/npx";
              args = [ "-y" "@upstash/context7-mcp@latest" ];
              description = "Up-to-date library documentation";
            };
          }
          # Obsidian MCP - conditional configuration based on implementation
          // (lib.optionalAttrs obsidianEnabled {
            obsidian =
              if mcpCfg.obsidian.implementation == "zero-dependency"
              then {
                command = "obsidian-mcp";
                args = [ mcpCfg.obsidian.vaultPath ];
                description = "Obsidian vault knowledge base (zero-dependency, read-only)";
              }
              else {
                command = "obsidian-mcp-rest";
                args = [ ];
                env = {
                  OBSIDIAN_API_KEY_FILE = mcpCfg.obsidian.restApi.apiKeyFile;
                  OBSIDIAN_HOST = mcpCfg.obsidian.restApi.host;
                  OBSIDIAN_PORT = toString mcpCfg.obsidian.restApi.port;
                  VERIFY_SSL = if mcpCfg.obsidian.restApi.verifySsl then "true" else "false";
                };
                description = "Obsidian vault with full CRUD via REST API plugin";
              };
          })
          # GitHub MCP server (if GitHub token available)
          // (lib.optionalAttrs (osConfig.age.secrets."api-github-token" or null != null) {
            github = {
              command = "github-mcp-server";
              args = [ ];
              env = {
                GITHUB_TOKEN_FILE = osConfig.age.secrets."api-github-token".path;
              };
              description = "GitHub repository integration";
            };
          });
      };

      # Generate JSON configuration with proper formatting
      onChange = ''
        echo "Claude Desktop MCP configuration updated"
        echo "Restart Claude Desktop for changes to take effect"
      '';
    };

    # Documentation for Claude Desktop MCP setup
    home.file.".config/Claude/MCP-README.md".text = ''
      # Claude Desktop MCP Configuration

      This configuration file is automatically generated by NixOS.
      Do not edit ~/.config/Claude/claude_desktop_config.json manually.

      ## Configuration Location

      Source: /home/${config.home.username}/.config/nixos/home/development/claude-desktop/mcp-config.nix
      Generated: ~/.config/Claude/claude_desktop_config.json

      ## Enabled MCP Servers

      ${lib.optionalString obsidianEnabled ''
      ### Obsidian (${mcpCfg.obsidian.implementation})
      ${if mcpCfg.obsidian.implementation == "rest-api" then ''
      - Mode: REST API (full CRUD operations)
      - Plugin Required: Obsidian Local REST API
      - Host: ${mcpCfg.obsidian.restApi.host}
      - Port: ${toString mcpCfg.obsidian.restApi.port}
      - SSL Verification: ${if mcpCfg.obsidian.restApi.verifySsl then "Enabled" else "Disabled"}
      '' else ''
      - Mode: Zero-dependency (read-only)
      - Vault Path: ${mcpCfg.obsidian.vaultPath}
      - No plugin required
      ''}
      ''}

      ### NixOS
      - Package and option queries
      - Prevents AI hallucinations about NixOS

      ${lib.optionalString (osConfig.age.secrets."api-github-token" or null != null) ''
      ### GitHub
      - Repository integration
      - PR automation and issue management
      ''}

      ### Context7
      - Up-to-date library documentation
      - Prevents coding hallucinations

      ## Applying Changes

      After modifying the configuration in NixOS:
      1. Rebuild your system: `just deploy` or `just p620`
      2. Restart Claude Desktop application
      3. MCP servers will be available in Claude

      ## Troubleshooting

      Check logs:
      - Claude Desktop: Check application console (View → Developer → Developer Tools)
      - MCP servers: Run manually to test (e.g., `obsidian-mcp-rest`)

      Verify configuration:
      - cat ~/.config/Claude/claude_desktop_config.json
      - Check for syntax errors in JSON

      ## Security Notes

      - API keys loaded at runtime (not in Nix store)
      - Secrets managed via agenix
      - Follow docs/NIXOS-ANTI-PATTERNS.md security patterns
    '';
  };
}
