# Generated by nixarchy-apply. Do not edit -- your files
# are ~/.config/nixarchy/{apps,services,advanced}.nix and
# this is regenerated from them on every apply.
{
  imports = [ ./nixarchy/apps.nix ./nixarchy/services.nix ./nixarchy/advanced.nix ];
}
